Benefícios do produto
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus pull request #18
Opened 2024-09-07 17:14 UTC by gabriel-fsantos

Atualização da seção _3.2.4 Benefícios do produto_ no arquivo `docs/especificacao.md`

2024-09-07 18:00 UTC, NicolasCBV requested changes

2024-09-07 18:00 UTC, NicolasCBV commented on docs/especificacao.md
> +| 3 | Clareza e simplicidade dos exercícios  | Essencial |
Acho que seria interessante unificar todos os benefícios em um só, deixando, como, por exemplo: "Facilidade no acesso de um amplo leque de exercícios"

2024-09-07 18:00 UTC, NicolasCBV commented on docs/especificacao.md
Talvez dê para colocar mais alguns benefícios da plataforma, como, por exemplo: "Acesso rápido e sem necessidade de cadastro dos idosos"

2024-09-07 21:08 UTC, Vinicius-O-Neves commented on docs/especificacao.md
Talvez nesse ponto traga a duvida de como o profissional vai encontrar se o idoso não estiver cadastrado

2024-09-07 21:12 UTC, Vinicius-O-Neves requested changes
Talvez adicionar algo que gere um roteiro de treino para os idosos também seja valido

2024-09-07 21:16 UTC, NicolasCBV commented on docs/especificacao.md
Nesse caso, o navegador apenas redireciona o idoso para o seu client de email e monta uma mensagem para o profissional, da uma olhada nesse exemplo: [https://icei-puc-minas-pmv-si.github.io/pmv-si-2023-2-pe1-t2-senectus/src/search-professionals.html](https://icei-puc-minas-pmv-si.github.io/pmv-si-2023-2-pe1-t2-senectus/src/search-professionals.html). Caso o dispositivo do usuário não tenha nenhum client, o email e telefone são fornecido na tela

2024-09-07 21:19 UTC, NicolasCBV commented
> Talvez adicionar algo que gere um roteiro de treino para os idosos também seja valido

Como funcionaria? Seria tipo acessar a API do ChatGPT e gerar um roteiro?

2024-09-07 22:25 UTC, gabriel-fsantos commented
@NicolasCBV @Vinicius-O-Neves Fiz os ajustes, porém não adicionei a ideia do roteiro, entendo que isso ainda vai ser discutido, podemos revisitar esses pontos após o fechamento do escopo do projeto, podemos ter ainda outras features novas que poderiam ser mencionadas como benefícios do produto.

2024-09-07 22:35 UTC, NicolasCBV commented
> @NicolasCBV @Vinicius-O-Neves Fiz os ajustes, porém não adicionei a ideia do roteiro, entendo que isso ainda vai ser discutido, podemos revisitar esses pontos após o fechamento do escopo do projeto, podemos ter ainda outras features novas que poderiam ser mencionadas como benefícios do produto.

Certo, por enquanto vamos deixar o PR aberto até domingo no fechamento da issue do [escopo do produto](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/issues/11). Vinicius, se você quiser, comenta mais sobre essa sua ideia lá no tópico pra que eu a @juliamascari e o @HgBertani tenhamos uma melhor noção

2024-09-09 23:19 UTC, NicolasCBV requested changes

2024-09-09 23:19 UTC, NicolasCBV commented on docs/especificacao.md
@gabriel-fsantos finalizamos a issue de escopo do produto, podemos adicionar mais um benefício referente a facilidade de acesso a informação sobre saúde devido ao componente de blog citado [aqui](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/blob/main/docs/especificacao.md#321-nome-do-produto-e-seus-componentes-principais), que tal?

2024-09-09 23:20 UTC, NicolasCBV approved these changes

2024-09-09 23:37 UTC, Vinicius-O-Neves commented
> > Talvez adicionar algo que gere um roteiro de treino para os idosos também seja valido
> 
> Como funcionaria? Seria tipo acessar a API do ChatGPT e gerar um roteiro? Ou seria algo mais manual na perspectiva do usuário?

O fisioterapeuta/personal faria mesmo

2024-09-09 23:37 UTC, Vinicius-O-Neves approved these changes

2024-09-09 23:39 UTC, merged