preenchimento "usúarios"
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus pull request #20
Opened 2024-09-08 22:12 UTC by juliamascari

## Resuma o seu Pull Request (PR) em até 5 linhas:

## Selecione o tipo de mudanças feitas:
- [ ] Bug fix
- [ ] Novas funcionalidades
- [x] Atualização da documentação
- [ ] Refatoração do código 
- [ ] Outro:

## Issues afetadas

| ID   | Issues         |           Link             |
| :--: |:-------------: | :------------------------: |
| #15  | Usuários do sistema  | (https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/issues/15) |

2024-09-08 22:59 UTC, NicolasCBV requested changes

2024-09-08 22:59 UTC, NicolasCBV commented on docs/especificacao.md
> +| Fisioterapeuta |	Usuário profissional da saúde que deseja encontrar novas formas de divulgação do seu trabalho com idosos. |
Talvez seria interessante deixarmos um pouco mais genérico, já que não existem diferenças nas funcionalidades que cada profissional da área da saúde pode ter dentro do sistema, no caso o foco sempre fica pra divulgar a sua marca. Além disso, podemos enriquecer mais a quantidade de atores colocando algum gestor de eventos ou algo do tipo, já que agora teremos um módulo só pra isso

2024-09-08 22:59 UTC, NicolasCBV commented on docs/especificacao.md
> +| Filho de Idoso |	Usuário que necessita contratar um profissional para auxiliar seu pai. |
Se achar necessário pode seguir a mesma lógica colocando "Familiar do idoso" ou algo do tipo

2024-09-09 18:11 UTC, juliamascari commented on docs/especificacao.md
> +| Fisioterapeuta |	Usuário profissional da saúde que deseja encontrar novas formas de divulgação do seu trabalho com idosos. |
Alterações feitas!

2024-09-09 21:15 UTC, NicolasCBV approved these changes

2024-09-09 21:16 UTC, merged