Personas
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus pull request #45
Opened 2024-10-17 03:57 UTC by juliamascari

## Resuma o seu Pull Request (PR) em até 5 linhas:

Criação dos seis perfis de personas, três profissionais de saúde e três idosos. 

## Selecione o tipo de mudanças feitas:
- [ ] Bug fix
- [ ] Novas funcionalidades
- [x] Atualização da documentação
- [ ] Refatoração do código 
- [ ] Outro:

## Issues afetadas

| ID   | Issues         |           Link             |
| :--: |:-------------: | :------------------------: |
| #30  | Criar Personas  | [Link](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/issues/30) |

2024-10-17 23:02 UTC, NicolasCBV requested changes

2024-10-17 23:02 UTC, NicolasCBV commented on docs/design.md
> +![Persona - Lucas](../.github/img/lucas.png)
Notei que a Amanda e o Lucas possuem objetivos e responsabilidades profissionais bem semelhantes, ambos gerenciam planos de treinamento e me deu a entender que ambos buscam intervir diretamente na vida de seus clientes para garantir uma qualidade de vida melhor. Podemos manter isso na Amanda e alterar as especificações do Lucas? Pensei em algo mais relacionado a divulgação de artigos por meio dos blogs que citamos nos documentos da etapa passada.

2024-10-20 15:25 UTC, juliamascari commented on docs/design.md
> +![Persona - Lucas](../.github/img/lucas.png)
Ajustado

2024-10-20 23:09 UTC, NicolasCBV approved these changes

2024-10-20 23:09 UTC, merged