Criação das páginas de Login e Cadastro
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus pull request #53
Opened 2024-10-27 01:19 UTC by juliamascari

## Resuma o seu Pull Request (PR) em até 5 linhas:

Criação das páginas de "sigin", "register" e "register-info".

## Selecione o tipo de mudanças feitas:
- [ ] Bug fix
- [x] Novas funcionalidades
- [ ] Atualização da documentação
- [ ] Refatoração do código 
- [ ] Outro:

## Issues afetadas

| ID   | Issues         |           Link             |
| :--: |:-------------: | :------------------------: |
| #36 | Criar página de login e cadastro | [Link](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/issues/36) |

2024-10-27 03:59 UTC, NicolasCBV requested changes

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/login.module.css
@juliamascari, estamos usando o styled components para poder aplicar o css em nossos componentes, observe o componente de rodapé que criamos para que você possa tentar utilizar de exemplo.

Neste [arquivo](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/blob/cad-log/src/components/common/Footer/FooterStyle.ts) criamos a estilização separada e abrindo crases para aplicar a estilização em forma de string, como se estivéssemos escrevendo um arquivo em css, mas dentro do próprio Javascript, e logo em seguida aplicamos a estilização realizando a importação da tag dentro de [src/components/common/Footer/AppFooter.tsx](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/blob/cad-log/src/components/common/Footer/AppFooter.tsx). Observe que em certos momentos utilizamos ${} para invocar uma arrow function que entrega o tema em forma de argumento, ou seja, você também não precisa citar explicitamente as cores pois toda a paleta já foi mapeada em themes que esta presente em [src/themes/theme.ts](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/blob/cad-log/src/themes/theme.ts).

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register-info.tsx
> +                <img className="login-img" src="/img/common/idoso_andando_de_bicicleta.jpg" alt="idosa meditando" />
O NextJs tende a disparar alertas e barrar os processos de build do aplicativo toda vez que utilizamos a tag img, o framework já possui uma tag especifica para isso que é a [\<Image/\>](https://nextjs.org/docs/pages/api-reference/components/image), neste caso peço que dê prioridade para o atributo ["priority"](https://nextjs.org/docs/pages/api-reference/components/image) quando fizer o uso desta tag para evitar problemas de carregamento. A regra de indicação da fonte em src se mantém a mesma para imagens locais e você agora será obrigada a usar o alt e o width e height, que são alteráveis via css apenas cite img para fazer referência a esta tag.

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register-info.tsx
> +                    <button type="button" className={styles.backButton} onClick={handleBack}>Voltar</button>
Dê uma olhada na base componentes padronizados que temos em [src/components/common](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/tree/cad-log/src/components/common), tanto o botão outline quanto o preenchido já existem e podem ser importados com:
```
import { AppButtonActionRect } from '@components/common/Buttons/AppButtonActionRect'
```
```
import { AppButtonActionRect } from '@components/common/Buttons/AppButtonLinkRectOutline.tsx
```

Ambos os componentes herdam todas as propriedades de Button do [NextUI](https://nextui.org/docs/components/button), como por exemplo o fullWidth para definir width em 100%. Existem algumas pequenas diferenças entre o componente que temos e o do NextUI, como por exemplo a inserção do texto que é obrigatória e deve ser feita via o atributo "text".

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register-info.tsx
Vou precisar que você remova este arquivo a passe todas as informações para o diretório src/app, o NextJs possui dois padrões de páginas, o pages e o app. Todos os diretórios que criamos dentro de app representa um endpoint, então uma pasta com o nome "login" vai ser convertido em /login e assim por diante, apenas copie o src/app/exercises para src/app/login, remove a pasta [categoryId] e comece a inserir tudo que criou aqui dentro de src/app/login/page.tsx, deixe a função preferencialmente desta forma:
```
export default function LoginScreen() {
  return (
    <ThemeProvider theme={theme}> {/*Injeção do tema do styled component*/}
      <NextUIProvider className="default"> {/*Injeção das configurações do NextUI*/}
      {/*Insira suas alterações aqui*/}
      </NextUIProvider>
    </ThemeProvider>
  )
}
```

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register-info.tsx
> +                <span>Para finalizar o cadastro da sua conta, por favor nos informe o que te trouxe aqui:</span>
Pode usar a tag p mesmo, o globals.css já vai tratar de estilizar corretamente

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register-info.tsx
> +                                    type="radio"
O NextUI já possui um componente especifico para lidar com marcadores que é o [Radio](https://nextui.org/docs/components/radio-group#controlled), no link que marquei eles possuem um exemplo perfeito, tenta seguir os seguintes passos, se baseando no exemplo deles:
- Instale o componente com ```npm install @nextui-org/radio```;
- Crie uma pasta dentro de src/components/ com o nome de login;
- Crie um componente AppOptions.tsx e dentro dele crie uma função exportável com o mesmo nome e utilize o exemplo que te mostrei, não esqueça de criar os dois botões de ações, caso contrário você será obrigada a compartilhar informações externas por meio de interfaces, igual os outros componentes estão fazendo;
- Demarque o RadioGroup e os seus filhos com uma classe ou id (esta propriedade deve ser citada na estilização);
- Dentro da pasta login crie um arquivo de estilização chamado OptionsStyle.ts;
- Aplique a estilização da mesma forma que citei anteriormente em AppFooterStyle;
- Envolva o componente de estilo dentro de AppOptions;
- Depois de criar o AppOptions.tsx, apenas importe ele no conteúdo da sua função e use como se fosse uma tag normal tipo assim ```<AppOptions/>```.

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register-info.tsx
> +export default SelectionForm;
Neste caso em que o framework esta completamente responsável por fazer o manuseio de seu componente é completamente ok e **deve** utilizar o export default, mas evite fazer isso com os componentes que você vai criar que não são páginas, como inputs ou Radios, pois isso pode causar conflitos de nomenclatura ao longo do código, dando a possibilidade de qualquer um nomear a importação da maneira que bem entender.

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register.tsx
> +        if (name === '' || email === '' || password === '') {
Ao realizar validações de campo, recomendo fazer o uso do zod, que é uma biblioteca de validação de objetos veja um exemplo [aqui](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/blob/cad-log/src/%40core/repositories/ExerciseRepo.ts), observe a exportação na linha 3 e a sua implementação, da linha 10 até a 42. Recomendo também que você faça a separação desta função em outro campo do sistema, pois isso já não está mais relacionado com a tela em si, mas com a regra de negócio, tente criar uma classe dentro de src/@models/services utilizando somente métodos estáticos e faça o uso da sua classe aqui nesta função. Caso ache muito difícil o uso do zod, mantenha somente a implementação desta validação na camada de services mesmo.

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register.tsx
> +        const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
O zod também possui validação de email usando a função ```z.string().email()``

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register.tsx
> +        localStorage.setItem('userEmail', email);
Não precisa tentar manipular nenhuma unidade de armazenamento, quando você fizer o pr vou me aprofundar mais na regra de negócio e fazer isso de maneira mais centralizada no código. Foque somente na validação dos campos mesmo.

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register.tsx
> +                        <a
Use ```<InternalLink/>```, que é o nosso componente de link já estilizado, ou importe o [```Link```](https://nextjs.org/docs/app/api-reference/components/link) do próprio NextJs, isso vai reduzir a taxa de carregamento entre uma página e outra, pois esses componentes foram feitos para realizar o recarregamento dos componentes que ainda não apareceram na tela, evitando um recarregamento total da tela do usuário. Você também não vai precisar citar o onClick ao usar esses componentes.

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register.tsx
Não esqueça de passar esse arquivo para o diretório app também.

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/register.tsx
> +                            <input
Parece que acabamos esquecendo de adicionar o componente de input, vou abrir um pr amanhã na sua branch, você aceita e dai é só importar o input padrão do projeto e usar aqui, erro meu, desculpa ai.

2024-10-27 03:59 UTC, NicolasCBV commented on src/pages/sigin.tsx
Não esqueça de passar esse arquivo para o diretório app também.

2024-10-27 04:02 UTC, NicolasCBV commented
@juliamascari tem bastante coisa que citei em um arquivo, mas que vale para os outros, tente aplicar todas as alterações de maneira homogênea no seu código. Devo estar disponível lá por final da tarde de amanhã, são muitas alterações então se precisar de ajuda não exite em me chamar. Outra coisa, observei alguns problemas de responsividade em todas as páginas que visualizei aqui, tenta usar o devtools do seu navegador pra descobrir onde está os erros de estilização ai.

2024-11-03 06:13 UTC, juliamascari reviewed
Criação das páginas em "app"

2024-11-03 15:28 UTC, NicolasCBV requested changes

2024-11-03 15:28 UTC, NicolasCBV commented on src/@core/services/postsignup/ValidateFormService.ts
> +        .max(320, 'Nome precisa ter no máximo 320 caracteres'),
Diminua a quantidade de caracteres que um nome poder ter pra 80, eu não acho que o nome do usuário vai acabar passando disso. Não esquece de mudar a mensagem de erro também.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/sigin/AppFormSigin.tsx
Volte com o componente original e sem alterações que deixei no pull request, isto está quebrando a importação usada em ```src/app/login/page.tsx```, onde este componente deveria estar originalmente sendo importado.

2024-11-03 15:28 UTC, NicolasCBV commented on src/@core/services/sigin/ValidateFormService.ts
Volte com o service original do login, isto esta quebrando as importações dos componentes desta página.

2024-11-03 15:28 UTC, NicolasCBV commented on src/@core/services/signup/ValidateFormService.ts
```src/@core/services/postsignup/ValidateFormService.ts``` já esta fazendo a mesma validação escolha um dos dois services para manter no código e remova o outro.

2024-11-03 15:28 UTC, NicolasCBV commented on src/app/login/page.tsx
> +import { AppFormLogin } from '@components/login/AppFormLogin'
Você alterou o nome dos arquivos e o nome do componente em si, como disse em algumas solicitações de mudanças acima, volte com o componente original que havia feito no pull request, retornando com os nomes dos arquivos e componentes que já haviam sido definidos para evitar que essa quebra de importação ocorra.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/signup/AppFormSignUp.tsx
> +          src="/img/login-register/idoso.jpg"
```src``` está usando uma imagem que não existe em ```/img```.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/postsignup/AppFormPostSignUp.tsx
> +          src="/img/login-register/idoso.jpg"
```src``` está usando uma imagem que não existe em ```/img```.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/postsignup/AppFormPostSignUp.tsx
> +        <label id="label">
Pode usar tag ```p``` mesmo, o globals.css já está cuidando da estilização e formatação de fonte desta tag.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/postsignup/FormPostSignUpStyle.tsx
> +    }
Mantenha assim apenas para telas abaixo dos 1000px de largura. Para telas acima disso use o ```grid``` com ```grid-template-columns``` e ```grid-area``` em cada radio pra controlar a posições que o mesmo vai ficar no grid da sua tag pai.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/postsignup/FormPostSignUpStyle.tsx
> +  #forms {
Confira o ```#forms``` de ```src/components/signup/FormSignUpStyle.ts```, você esqueceu de aplicar o ```overflow-y``` e provavelmente mais alguns outros atributos, como o ```height``` e isso está quebrando o layout.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/postsignup/FormPostSignUpStyle.tsx
> +    padding: 6rem 0 0 6rem;
Veja novamente esta tag e corrija a aplicação de ```padding``` em conjunto com o posicionamento dos elementos. Os outros formulários não estão se baseando no ```padding``` para posicionar seus elementos internos, eles estão usando o ```grid-template-rows``` e ```grid-template-columns```.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/postsignup/FormPostSignUpStyle.tsx
> +  }
Não estilize elementos que já foram criados e estilizados, como os botões padrões, isso vai causar quebras inesperadas no layout.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/postsignup/FormPostSignUpStyle.tsx
> +    margin-left: 25%;
Remove o ```margin-left``` e define o ```width``` com 100%. Para telas menores que 400px eu recomendaria usar o ```flex-direction: column```.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/postsignup/AppFormPostSignUp.tsx
> +          />
Substitui o ```AppButtonLinkRect``` para ```AppButtonActionRectOutline``` com o ```fullWidth```, envolva este componente com o ```Link``` de ```next/link``` e no arquivo de estilização defina o ```width``` deste link em 100%. Todos os botões que são links possuem uma largura diferente dos botões padrões e no protótipo estes botões devem ter larguras iguais nesta tela.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/postsignup/FormPostSignUpStyle.tsx
> +    object-fit: cover;
Confira novamente o ```src/components/signup/FormSignUpStyle.ts```, a imagem não esta sendo removida em telas abaixo dos 1000px.

2024-11-03 15:28 UTC, NicolasCBV commented on src/components/postsignup/FormPostSignUpStyle.tsx
> +  overflow: hidden;
Confira ```src/components/signup/FormSignUpStyle.ts``` pra definir o ```grid``` e ```grid-template-columns``` e fazer a separação da tela corretamente. Não se esqueça de checar o ```@media``` pra ver como telas menores devem reagir.

2024-11-03 15:36 UTC, NicolasCBV commented
> Ajustes das páginas de "sign in", "sign up" e "post-sign up" em "app", "components" e "@.core"

@juliamascari a tela de login já havia sido criada e pelo que observei o sigin representa ela, algumas das minhas revisões estão citando exatamente isso. Não vejo problema na mudança de nomes dos arquivos, porém ou você altera os caminhos de importações destes componentes nos arquivos, ou volte com o nome dos componentes do login aos que eram antes pois a página de login está quebrada.

2024-11-05 20:30 UTC, NicolasCBV approved these changes

2024-11-05 20:30 UTC, merged