Feature/appointment solicitation
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus pull request #59
Opened 2024-10-30 00:48 UTC by Vinicius-O-Neves

## Resuma o seu Pull Request (PR) em até 5 linhas:
Criando a tela de solicitação de consulta

## Selecione o tipo de mudanças feitas:
- [ ] Bug fix
- [x] Novas funcionalidades
- [ ] Atualização da documentação
- [ ] Refatoração do código 
- [ ] Outro:

| ID   | Issues         |           Link             |
| :--: |:-------------: | :------------------------: |
| #39  | Tela de consulta  | [Link](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/issues/39) |

2024-10-30 16:10 UTC, NicolasCBV requested changes

2024-10-30 16:10 UTC, NicolasCBV commented on public/img/common/ic_email.svg
React Icons já tem um ícone de email chamado FaEnvelope, todas as fontes do projeto foi feita com base no font awesome, confira [aqui](https://fontawesome.com/search) biblioteca de ícones deles

2024-10-30 16:10 UTC, NicolasCBV commented on public/img/common/ic_calendar.svg
React Icons já tem um ícone de calendário chamado FaCalendarDays, todas as fontes do projeto foi feita com base no font awesome, confira [aqui](https://fontawesome.com/search) biblioteca de ícones deles

2024-10-30 16:10 UTC, NicolasCBV commented on public/img/common/ic_location.svg
React Icons já tem um ícone de localização chamado FaLocationDot, todas as fontes do projeto foi feita com base no font awesome, confira [aqui](https://fontawesome.com/search) biblioteca de ícones deles

2024-10-30 16:10 UTC, NicolasCBV commented on public/img/common/ic_phone.svg
React Icons já tem um ícone de telefone chamado FaPhone, todas as fontes do projeto foi feita com base no font awesome, confira [aqui](https://fontawesome.com/search) biblioteca de ícones deles

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/page.tsx
> +        const response = await fetch('/inMemoryDb/professionals.json');
Você não precisa fazer uma requisição para coletar o json, basta importar diretamente o json usando a keyword ```import```, isso vai evitar um loading desnecessário que é gerado com o useEffect

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/page.tsx
> +            <AppSearchNotFound text="Nenhum exercício encontrado." />
Muda o atributo text pra "Nenhum profissional encontrado."

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/page.tsx
> +          <h1>Pesquisar profissional</h1>
Colocar o atributo ```className="prettify-title"``` pra definir o quadrado roxo de fundo, essa classe foi definida lá em globals.css

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCard.tsx
> +    icon: string
Troca a string pra ReactNode, assim você vai poder usar o react icons e definir todos os ícones que citei acima

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCard.tsx
> +                <p style={{ fontWeight: 'bold' }}>{professional.role}</p>
O cargo do profissional não tem bold nos protótipos

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCard.tsx
> +                    marginBottom: '4px'
O nome do profissional não tem bold, além disso, acredito que fique mais responsivo se você colocasse fontSize de 1 rem

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCard.tsx
> +                        icon="/img/common/ic_calendar.svg"
O botão que criamos não reconhece texto, apenas ReactNode. Como falei acima, substituia pelo react icons utilizando o FaCalendarDays. Além disso, vou precisar que você altere todos os botões que criamos, mudando o atributo endContent para startContent, pro ícone ser definido no começo e não no final do botão.

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCard.tsx
> +                </div>
Tira esse componente que esta envolvendo o botão e coloca o atributo fullWidth no botão, assim ele vai ocupar toda a largura do card.

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCardStyles.ts
> +    border: 4px solid ${({ theme }) => theme.color.onHoverSecondaryBgColor};
Coloca uma borda mais suave, tipo 2px e troca a cor, todas as cores que criamos para borda esta dentro de theme.border.color, no caso só temos o default mesmo

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCardStyles.ts
> +    border-radius: 4rem 4rem 4rem 4rem;
A borda do cargo ficou muito grande, os temas já tem uma borda padrão, usa ```theme.border.radius.md```

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCardStyles.ts
> +    &:hover {
Tira o hover do card, o card em si não tem interação, quem tem é o botão dentro dele. Aproveita e remove o ```transition``` logo acima

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCardStyles.ts
> +    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1)
O card não tem arredondamento de borda, pode tirar. Aproveita e tira o box-shadow também

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCardStyles.ts
> +    align-items: left;
```left``` não existe no css, pode trocar pra ```start``` que é o equivalente

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCardStyles.ts
> +    marginTop: 8px;
```marginTop``` não existe, troca pra ```margin-top```

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCardStyles.ts
> +export const ProfessionalsItemsStyle = styled.div`
Define um width de 100% aqui pra evitar quebra no layout

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCardStyles.ts
> +export const ProfessionalItemStyle = styled.div`
Cita o ```p``` aqui dentro assim:
```
& p {
  white-space: nowrap;         /* Impede o texto de quebrar para a próxima linha */
  overflow: hidden;            /* Oculta o conteúdo que passa do limite do elemento */
  text-overflow: ellipsis;    /* Substitui o que foi ocultado por "..."  */
}
```

2024-10-30 16:10 UTC, NicolasCBV commented on src/components/common/Inputs/SearchBar/AppSearchBarStyles.ts
> +  }
Pode tirar essa definição de largura aqui, algumas questões de responsividade foram corrigidas na branch main, então isso não é necessário. Mantenha somente a mudança de fonte mesmo

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/AppointmentsSolicitationStyles.ts
> +    gap: 16px;
Muda de ```gap``` para ```grid-gap``` e deixa um 1rem, é a mesma coisa que 16px

2024-10-30 16:10 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/AppointmentsSolicitationStyles.ts
> +    }
Da uma olhada nesses breakpoints que você definiu porque a tela ainda esta quebrando

2024-10-30 16:16 UTC, NicolasCBV requested changes

2024-10-30 16:16 UTC, NicolasCBV commented on package-lock.json
Consegue tirar esse lockfile desta branch e citar ele no .gitignore? As mudanças do seu pr subiram pra 12K por conta disso

2024-10-30 16:16 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/AppointmentsSolicitationStyles.ts
Move estes estilos lá pra ```components```, só pra deixar mais organizado

2024-10-30 16:16 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/page.tsx
Muda o nome da pasta, se não vamos ser obrigados a passar o id da solicitação e ele ainda não existe, deixa a pasta como ````src/app/appointments/new```, é o link que a página inicial de consultas está redirecionando

2024-10-31 00:33 UTC, Vinicius-O-Neves commented on public/img/common/ic_email.svg
Feito

2024-10-31 00:33 UTC, Vinicius-O-Neves commented on public/img/common/ic_location.svg
Feito

2024-10-31 00:33 UTC, Vinicius-O-Neves commented on src/app/appointments/[solicitation]/page.tsx
> +        const response = await fetch('/inMemoryDb/professionals.json');
Feito

2024-10-31 00:33 UTC, Vinicius-O-Neves commented on public/img/common/ic_phone.svg
Feito

2024-10-31 00:33 UTC, Vinicius-O-Neves commented on public/img/common/ic_calendar.svg
Feito

2024-10-31 00:35 UTC, Vinicius-O-Neves commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCard.tsx
> +                <p style={{ fontWeight: 'bold' }}>{professional.role}</p>
ah parece olhando aqui

2024-10-31 00:36 UTC, Vinicius-O-Neves commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCard.tsx
> +    icon: string
Criei um tipo já que agr nao vai vir do publix

2024-10-31 00:42 UTC, Vinicius-O-Neves commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCard.tsx
> +                </div>
o div to usando para ter um margin, senao fica grudado

2024-10-31 00:47 UTC, Vinicius-O-Neves commented on src/components/common/Inputs/SearchBar/AppSearchBarStyles.ts
> +  }
Conforme falado pelo whatssap, foi para o responsivo

2024-10-31 00:48 UTC, Vinicius-O-Neves commented on src/app/appointments/[solicitation]/AppointmentsSolicitationStyles.ts
> +    }
Estranho, deve ser pelo monitor...consegue puxar ai e ver os valores que quebra no seu?

2024-10-31 00:49 UTC, Vinicius-O-Neves commented on package-lock.json
Remover não posso, senão toda vez que puxar para rodar o projeto irei precisar instalar tudo novamente

2024-10-31 00:49 UTC, Vinicius-O-Neves commented on src/app/appointments/[solicitation]/AppointmentsSolicitationStyles.ts
Será que vale? Esses cards nao serao compartilhados

2024-10-31 00:54 UTC, Vinicius-O-Neves commented
Deixei o nome como 1.2 rem, ficou melhor mesmo para ver

2024-10-31 00:57 UTC, Vinicius-O-Neves commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCardStyles.ts
> +    border: 4px solid ${({ theme }) => theme.color.onHoverSecondaryBgColor};
Feito

2024-10-31 01:04 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/AppointmentsSolicitationStyles.ts
Sim, a pasta de components não é apenas para componentes que são compartilhados, por isso existe a common dentro de components. Por padrão o Nextjs vê os arquivos da pasta app como páginas e não componentes

2024-10-31 01:24 UTC, NicolasCBV requested changes

2024-10-31 01:24 UTC, NicolasCBV commented on src/app/appointments/new/AppointmentsSolicitationStyles.ts
> +        grid-template-columns: repeat(2, 1fr);
Altera pra 720px e defini o width com fit-content

2024-10-31 01:24 UTC, NicolasCBV commented on src/app/appointments/new/AppointmentsSolicitationStyles.ts
> +    @media (max-width: 460px) {
Muda pra 540px

2024-10-31 01:34 UTC, NicolasCBV commented on src/app/appointments/[solicitation]/professional_card/ProfessionalCard.tsx
> +                <p style={{ fontWeight: 'bold' }}>{professional.role}</p>
Ss, ele era pra ser medium/500, mas visualmente falando não está tendo muita diferença do peso normal

2024-10-31 01:54 UTC, NicolasCBV commented on src/components/common/Inputs/SearchBar/AppSearchBarStyles.ts
> +  }
Tenta dar um checkout no SearchAndFilter, SearchBar e o AppSelect da branch feat/consultas, estou achando que no final das contas as duas branches estão tentando resolver o mesmo problema de responsividade e isso pode acabar quebrando esse componente. Só toma cuidado porque tem breaking change nos valores das funções.

2024-10-31 01:56 UTC, NicolasCBV requested changes

2024-10-31 01:56 UTC, NicolasCBV commented on src/app/appointments/new/professional_card/ProfessionalCardStyles.ts
> +    width: 16rem;
Troca pra 13rem, os cards no protótipo estão bem menores do está sendo exibido atualmente

2024-10-31 02:03 UTC, NicolasCBV commented
> Deixei o nome como 1.2 rem, ficou melhor mesmo para ver

Quantos caracteres cabem sem quebrar o layout usando este tamanho de fonte? Havia solicitado a mudança pensando mais em deixar responsivo em telas menores, saber essa informação vai ser importante, pois vamos precisar fazer uma tratativa nos nomes dos usuários, já caímos nesta situação no [botão de configuração](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/pull/55#discussion_r1819801817) que vamos adicionar.

2024-10-31 02:38 UTC, Vinicius-O-Neves commented on src/components/common/Inputs/SearchBar/AppSearchBarStyles.ts
> +  }
Aparentemente não deu problema nao, aqui ele vai pegar  a linha inteira e lá ele está no input

2024-10-31 02:40 UTC, Vinicius-O-Neves commented on src/app/appointments/[solicitation]/AppointmentsSolicitationStyles.ts
Feito

2024-10-31 02:48 UTC, Vinicius-O-Neves commented
![image](https://github.com/user-attachments/assets/5173cee7-6400-4575-92c1-f4a01a833767)
Como está com o vw no search

![image](https://github.com/user-attachments/assets/02d0d622-73f4-4cd2-8043-e9b056222b21)
Antes ficava menor, sem a parte em vermelho

2024-10-31 02:49 UTC, Vinicius-O-Neves commented
> > Deixei o nome como 1.2 rem, ficou melhor mesmo para ver
 
> Quantos caracteres cabem sem quebrar o layout usando este tamanho de fonte? Havia solicitado a mudança pensando mais em deixar responsivo em telas menores, saber essa informação vai ser importante, pois vamos precisar fazer uma tratativa nos nomes dos usuários, já caímos nesta situação no [botão de configuração](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/pull/55#discussion_r1819801817) que vamos adicionar.

Está suportando até 18 caracteres, sendo 2 espaços

2024-10-31 21:10 UTC, NicolasCBV commented
> Antes ficava menor, sem a parte em vermelho

Provavelmente deve ser porque você não deu checkout em todos os componentes e estilos do input, quando fiz isso ficou assim pra mim:
![bug-print-senectus](https://github.com/user-attachments/assets/d5ef7846-1c88-418a-a532-52b6dd8f2906)

Agora está rodando certinho, subi um [pull request](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/pull/61) pra sua branch, da uma olhada lá.

2024-10-31 21:38 UTC, Vinicius-O-Neves commented
> > Antes ficava menor, sem a parte em vermelho
> 
> Provavelmente deve ser porque você não deu checkout em todos os componentes e estilos do input, quando fiz isso ficou assim pra mim: ![bug-print-senectus](https://private-user-images.githubusercontent.com/92616145/382116369-d5ef7846-1c88-418a-a532-52b6dd8f2906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MTA5NzYsIm5iZiI6MTczMDQxMDY3NiwicGF0aCI6Ii85MjYxNjE0NS8zODIxMTYzNjktZDVlZjc4NDYtMWM4OC00MThhLWE1MzItNTJiNmRkOGYyOTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDIxMzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2Yjc2OGFmYjI0MzBmOWVhMzNlNDY5MjhmNGFjMTkyOTU1MjE3MjM1OWM3ZWI1Zjc3ZWVmNmU3Mjk1MWU2NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aC_AclWdicYLkCpltVPEHQHUw1pUWKMrO03psGoJUfs)
> 
> Agora está rodando certinho, subi um [pull request](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/pull/61) pra sua branch, da uma olhada lá. O eslint acabou formatando algumas linhas a mais, não precisa estranhar isso.

eita que estranho ashauhsauha porque adicionei o width somente o search

2024-10-31 21:41 UTC, NicolasCBV commented
@Vinicius-O-Neves subi o [pull request](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/pull/63/files) do formulário e da home já, você consegue envolver o botão dos cards com a tag ```Link``` do ```next/link``` só pra redirecionar pra URL /appointments/id só pra encerrar o fluxo?

2024-11-03 15:38 UTC, NicolasCBV approved these changes

2024-11-03 15:38 UTC, merged