Feat/consultas form
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus pull request #63
Opened 2024-10-31 21:37 UTC by NicolasCBV

## Resuma o seu Pull Request (PR) em até 5 linhas:
Adicionar tela de formulário do idoso no módulo de consultas.

## Selecione o tipo de mudanças feitas:
- [ ] Bug fix
- [X] Novas funcionalidades
- [ ] Atualização da documentação
- [ ] Refatoração do código 
- [ ] Outro:

## Issues afetadas
| ID   | Issues         |           Link             |
| :--: |:-------------: | :------------------------: |
| #39  | Módulo de gestão de consultas  | [Link](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/issues/39) |

2024-11-01 12:55 UTC, Vinicius-O-Neves requested changes
Talvez vale para a próxima etapa, mas poderíamos deixar os estilos dentro do próprio componente daqueles que forem comuns

2024-11-01 12:55 UTC, Vinicius-O-Neves commented on src/components/appointments/form/AppAppointmentsForm.tsx
> +// Vou manter estático e retornar logo em seguida com a aplicação da regra de negócio
Adiciona um todo para nao esquecermos

2024-11-01 14:46 UTC, NicolasCBV commented on src/components/appointments/form/AppAppointmentsForm.tsx
> +// Vou manter estático e retornar logo em seguida com a aplicação da regra de negócio
Isso ai é referente a tarefa de adição de regra de negócio no sistema, acabei de criar [aqui](https://github.com/ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t2-g2-senectus/issues/64).

2024-11-01 14:48 UTC, NicolasCBV commented
> Talvez vale para a próxima etapa, mas poderíamos deixar os estilos dentro do próprio componente daqueles que forem comuns

Pode criar uma issue usando o template de funcionalidade e adicionar a tag da etapa 4? Ai na próxima etapa a gente discute sobre ela.

2024-11-03 00:13 UTC, Vinicius-O-Neves approved these changes

2024-11-03 00:49 UTC, merged